### PR TITLE
Adjustments to s4g001.md, and beyond.

### PR DESCRIPTION
**Pull request by StevenBlack**
This Pull Request contains several facets, and is expected to serve as a basis for further discussion because potentially hundreds of future PRs depend on stuff like this.

**Take Note**:  "*LGTM, merge this.*" is an acceptable response 😊

Many things in this PR come from experience porting [INTL](https://github.com/StevenBlack/intl) documentation to markdown.

Things of particular note here:

- [ ] file `sg4001.md` is renamed `trim_functions.md` and references adjusted, everywhere.
- [ ] Mixed case plaintext replaced with mixed case, code-tag-enclosed `ALLTRIM()`, `LTRIM()`, `RTRIM()`, `TRIM()`, everywhere.
- [ ] In `trim_functions.md` (formerly `sg4001.md`) inline code references are  code-tag-enclosed.
- [ ] Text lines are limited to 120 characters wide in `trim_functions.md` (formerly `sg4001.md`) for editability.

See the seven changed files for more detail.

Many of these steps are automatable, in whole of in part.

### CODE REVIEW

**Comment by DougHennig** [comment]
Since the Markdown files were generated by processing the HTML files that made up the CHM for the book, anything we can do to update the conversion code and regenerate the Markdown files will be vastly better than manually editing the files.

1. While doing the conversion, my first thought was to rename the files. However, I quickly realized that would be a manual process because many topics combine functions, such as s4g001 (the one you changed, which is about the TRIM functions) and s4g049, which combines COS(), SIN(), and other trig functions but also PI(). I didn't relish the idea of going through almost 900 topics and figuring out what name to use for each of them. Of course, once the naming is decided, it'd be easy: put the old and new names into a table and during generation of the Markdown files lookup the old name (for the name of the document as well as all links) and substitute the new one. So, rather than editing each topic individually, if someone wants to take the time to determine what name to assign to each file and create the table, I'm fine with adjusting the conversion code to handle that.

2. Great idea. This can be automated by updating the conversion code to look for keywords in the text and tagging them.

3. This is going to be hard to automate since the code can be anything and thus we need a parser. Let's leave this until the Markdown regeneration process is completed unless someone comes up with a way it can be automated.

4. This is easily done. In fact, the HTML files I used as the source for the Markdown have line breaks and I made the conversion code remove them. The reason I did that is because if someone uses a real Markdown editor (I use Markdown Monster) to edit the files, having line breaks in paragraphs will be a PITA to deal with. For example, if you add a couple of words in the first sentence of a paragraph, now all the line breaks in the paragraph are wrong and have to be redone.

**Comment by StevenBlack** [comment]
I didn't know the process is still re-entrant.

***For file names***.... I have [WebStorm](https://www.jetbrains.com/webstorm/) in my toolchain, so changing a file name, and all its references in the file system, is trivial, and 100%.  The harder issue would be, what to name the file.  For example `ANSITOOEM()` and `OEMTOANSI()` is the same file.

This might be a helpful idea... in the Wiki code, I have pre-processors to tokenize things, for example code blocks, and post-processes that replace the tokens with the original contents, so wiki parsers don't mangle things like code blocks, and islands that parser code should not touch.  `STREXTRACT()` and `STRTRAN()` are just wonderful for that.  

The strings `[```foxpro]+CHR(13)` and `[```]+CHR(13)` will serve as fine `STREXTRACT()` delimiters.  So will `<code>` and `</code>` and, of course, `<pre>` and `</pre>`.

**Comment by StevenBlack** [comment]
In Markdown, double carriage return is a line break, single carriage returns are ignored. Try it!

**Comment by DougHennig** [comment]
Issue 1. One thing that occurred to me is that we could name the file after the first word in its title, stripping out all but alphas. So, s4g001, which is "AllTrim(), LTrim(), RTrim(), Trim()", would be alltrim.md. It means the title doesn't include all functions/commands the topic covers but it's certainly better than s4g001.md and saves someone assigning names to close to 900 topics. Another possibility is to use the entire title with underscores replacing spaces, so s4g001 would be alltrim_ltrim_rtrim_trim.md. The main issue with that is some of the topics cover a ton of commands so the title would have to be trimmed for length.

Issue 3. The HTML to Markdown conversion code does something similar to your pre- and post-processing: it tokenizes code blocks and tables, then does replacements, then puts them back. The issue is inline code within paragraphs: an example like STRTRAN(SomeField, "SomeValue", "SomeOtherValue") won't match a simple lookup of STRTRAN() so a parser would be needed to identify and tag code like that.

Issue 4. The issue is that while line breaks render properly, they may not in the editor. I'm not sure how other editors work but, as you can see in this image, Markdown Monster displays line breaks as line breaks in the editor (the left panel) while rendering properly (the right panel). That makes editing the text a PITA.

s4g001

**Comment by StevenBlack** [comment]
@DougHennig The INTL conversion taught me, HTML to Markdown conversion only takes you so far.  Thereafter, at some juncture, gotta go rogue.  I know you know this.  Seems close to that point now.

Aren't line breaks supposed to render as line breaks, in the editor?  That's how all the markdown apps I've tried they all work.   I used VS Code for the INTL conversion, despite having a raft of MD editors at my disposal.  

As for point #2, the regex capabilities of VS Code take us pretty far.  It's an iterative process.  Typically a regex will fix 100 instances, say, but create five to ten hidden gotchas.  So it's a divide and conquer exercise.

I didn't use VFP at all for the INTL documentation conversion but, in hindsight, I should have, for tokenizing.  Here's what I might have done.

1. Physically tokenize the works.  Replace all code blocks, code islands, **and tables** with UUID strings, or some other unique token, and use the token as a lookup in a table that stores the code blocks.

2. THEN regex-find-and-replace everything in text, and eyeball all the code records to see if anything needs doing there.

3. Repeat the process, focusing on the  `<table>...</table>` islands.  The table elements might be better treated in VFP. 

4. Backfill all the tokens.

With a `git commit ...` between each major and minor step, to save work.  I learned this the hard way.

You know what's a real blessing here?  The `wdwddd.md` pattern in file names.  Those are unique and distinct, and a pleasure to search and replace.

I could make a case that everything should go into a single markdown file, and the `wdwddd.md` markers become references for hyperlinking around.  Certainly a single markdown file makes the find/replace problem easier.

VSCode is awesome for processing a large file, since you can see all the matching search hits in the sidebar, and it's easy to audit and eyeball a sample of hits before pulling the trigger.

**Comment by TamarEGranor** [comment]
Just getting a first chance to look at all this. I'm pretty sure I have the VFP tables that were used to map language elements to the various s4gnnn documents, if they'll help. The reason the sections are named like that, of course, is that they can contain multiple language elements. I don't remember all the details of how we did it. (After all, we first did this 25 years ago!) But if the data will help, let me know.

**Comment by DougHennig** [comment]
Thanks. The data and all the code to generate the HTML and Markdown documents is in the Source repository (https://github.com/HackFox/Source). I used the tables to help with a few things in converting to Markdown.

**Comment by DougHennig** [comment]
Steve, I left line breaks in all of the other documents, just not the s4*.md. As I edited the other documents in Markdown Monster, I found that as I added new text, the line break positions didn't change so the lines got longer than they were originally unless I wanted to take the time to adjust them. Not a big deal, I guess, but I prefer editing like Word does: automatically move text within the lines of a paragraph to fit the view port.

The tokenizing process I used is almost identical (in concept, anyway) to what you suggested.

Unless someone has a suggestion to provide names for the almost 900 documents, I'm going to leave them as is.

**Pull request closed without merging**
