### PR TITLE
Update the readme: remove erroneous references to db2 files, add brief instructions for contributors.

### PR DESCRIPTION
**Pull request by StevenBlack**

### CODE REVIEW

**Comment by DougHennig** [comment]
I don't understand removing the references to the two tables. They're both in the Source folder of the Source repository (https://github.com/HackFox/Source) as DB2 files and anyone who wants to contribute to HackFox would likely find them useful as locators for topic files by keyword.

**Comment by StevenBlack** [comment]
Are these artefacts required for this repo?  If so, then they should be in this repo.  

If these artefacts are not required for this repo, then there is no need to mention them, particularly in the root readme.

Do these files need to be synced with changes in this repo, then the files definitely should be in the repo, and this highly convoluted dependent relationship should be documented.

I can imagine no reason why these files exist beyond this point.

**Comment by StevenBlack** [comment]
See... here's the thing.

The *ethos* of git is, a one-liner gives you everything you need.  For example...

```
git clone https://github.com/HackFox/hackfox.github.io.git
```

... gives you a subfolder named `hackfox.github.io` and you are one hundred percent, good-to-go, with everything needed to stay current, and contribute on an onging basis.

This is in stark contrast with old epochs, when we had to download a .zip file, pick a folder to unzip it, and we end up with a disconnected copy buried in an arbitrary place with no connection back to `origin`, no way to keep subsequent changes and improvements synchronized.

What we have presently is, repo A referring to repo B about files in repo B that need to be transformed in order to be useful in the context of repo B, all of which is **not** the object of discourse, repo A.

I suppose the way it's imagined to work is we would *also* `git clone` repo B, then somewhere and somehow resolve paths between repo A and repo B, then run some magic on repo B to get `.dbf` files from `db2` files (which are not native `cursortoxml()` transformations but require something from repo C (somwehere)) .... honestly, this is just brain-dead stupid.

What we have presently is a conflation that ignores how far software development has progressed and evolved, especially in facets of community involvement in ongoing development.

If this is not what you want, I suggest putting everything in a .zip file that dinosaurs can download and unzip and forever be disconnected.

But this being in Github, it's helpful to keep things in-line with the way git works on a fundamental level.  The acid test is, one `git clone` command should be all anybody needs to use and contribute to the product.

Because it really is that easy, `git clone...` in 10Million-plus other repositories, here.

**Comment by DougHennig** [comment]
Fair enough. I guess in hindsight you don't need those tables to find a topic: you can just see the name of the document in the browser address bar after you've navigated to it, and then you know what to edit.

**Comment by StevenBlack** [comment]
... and also, in environments where the command window isn't decrepit and sorry-as, `grep` and [`ack`](https://beyondgrep.com/install/) exist and you can find anything, and all instances of it, in subsecond time.

**Pull request merged**
